language:
  - swift
osx_image: xcode11
script:
  - swift test -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.14"
  - xcodebuild -scheme CoreDataJsonParser -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.0,name=iPhone 11" build test
