//
//  TestJson.swift
//  CoreDataJsonParser
//
//  Created by Alex Belozierov on 9/23/19.
//  Copyright © 2019 Alex Belozierov. All rights reserved.
//

import XCTest
@testable import CoreDataJsonParser

extension Json {
    
    static let test: Json = {
        let data = jsonString.data(using: .utf8)!
        return Json(data: data)!
    }()
    
}

private let jsonString =
#"""
[
    {
        "id":"5d4980db9177a900015efa1b",
        "body":null,
        "owner":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "recipient":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "commentsCount":2,
        "reactionsCount":1,
        "createdDate":"2019-08-06T13:30:03.890Z",
        "lastModifiedDate":"2019-08-06T13:30:03.889Z",
        "media":[
            {
                "id":"5d4980db9177a900015efa2a",
                "content":"https://image.shutterstock.com/image-photo/white-transparent-leaf-on-mirror-600w-1029171697.jpg",
                "type":"PHOTO",
                "fileType":"image/jpeg",
                "isInFavorite":false,
                "owner":{
                    "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
                    "firstName":"Alex",
                    "lastName":"Belozierov"
                },
                "order":0,
                "createdDate":"2019-08-06T13:30:03.889Z",
                "lastModifiedDate":"2019-08-06T13:30:03.889Z",
                "advertised":false
            }
        ],
        "location":null,
        "linkPreview":null,
        "settings":{
            "privacySettings":"FRIENDS",
            "commenting":true,
            "postponePublication":null,
            "postponePublicationDate":null
        },
        "originPost":null,
        "taggedFriends":[
        ],
        "sharesCount":0,
        "sharedPost":null,
        "isContentUnavailable":false,
        "isAdvertised":false,
        "isLiked":true,
        "isAdvertisable":true
    },
    {
        "id":"5d4410154b59140111c66510",
        "body":"Таким чином \"Хаббл\" і багато інших космічних апаратів орієнтуються в космосі - це називається гіроскопічним ефектом.",
        "owner":{
            "uuid":"fba346fb-f3f5-4df5-aa47-9c13448f365e",
            "firstName":"Ivan",
            "lastName":"petrenko"
        },
        "recipient":{
            "uuid":"fba346fb-f3f5-4df5-aa47-9c13448f365e",
            "firstName":"Ivan",
            "lastName":"petrenko"
        },
        "commentsCount":0,
        "reactionsCount":0,
        "createdDate":"2019-08-02T10:27:33.237Z",
        "lastModifiedDate":"2019-08-02T10:39:59.444Z",
        "media":[
            {
                "id":"5d4412ff4b59241001c66530",
                "content":"https://image.shutterstock.com/image-photo/white-transparent-leaf-on-mirror-600w-1029171697.jpg",
                "type":"PHOTO",
                "fileType":"image/jpeg",
                "isInFavorite":false,
                "owner":{
                    "uuid":"fba346fb-f3f5-4df5-aa47-9c13448f365e",
                    "firstName":"Ivan",
                    "lastName":"petrenko"
                },
                "order":0,
                "createdDate":"2019-08-02T10:39:59.443Z",
                "lastModifiedDate":"2019-08-02T10:39:59.443Z",
                "advertised":false
            },
            {
                "id":"5d4410154b59140001c6650f",
                "content":"https://image.shutterstock.com/image-photo/white-transparent-leaf-on-mirror-600w-1029171697.jpg",
                "type":"VIDEO",
                "fileType":"video/mp4",
                "isInFavorite":false,
                "owner":{
                    "uuid":"fba346fb-f3f5-4df5-aa47-9c13448f365e",
                    "firstName":"Ivan",
                    "lastName":"petrenko"
                },
                "order":0,
                "createdDate":"2019-08-02T10:27:33.235Z",
                "lastModifiedDate":"2019-08-02T10:39:59.441Z",
                "advertised":false
            }
        ],
        "location":{
            "id":"5d4412ff4b59140111c6652f",
            "name":"London",
            "description":"London, UK",
            "icon":null,
            "latitude":51.5073509,
            "longitude":-0.12775829999998223
        },
        "linkPreview":null,
        "settings":{
            "privacySettings":"EVERYONE",
            "commenting":true,
            "postponePublication":null,
            "postponePublicationDate":null
        },
        "originPost":null,
        "taggedFriends":[
            {
                "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
                "firstName":"Alex",
                "lastName":"Belozierov"
            }
        ],
        "sharesCount":0,
        "sharedPost":null,
        "isContentUnavailable":false,
        "isAdvertised":false,
        "isLiked":false,
        "isAdvertisable":false
    },
    {
        "id":"5d403614f8b8101101a6fdf3",
        "body":"sdasdadasdada",
        "owner":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "recipient":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "commentsCount":1,
        "reactionsCount":0,
        "createdDate":"2019-07-30T12:20:36.474Z",
        "lastModifiedDate":"2019-07-30T12:20:36.473Z",
        "media":[
        ],
        "location":null,
        "linkPreview":null,
        "settings":{
            "privacySettings":"EVERYONE",
            "commenting":true,
            "postponePublication":null,
            "postponePublicationDate":null
        },
        "originPost":{
            "id":"5d4035b32a8c780111784dfa",
            "body":null,
            "owner":{
                "uuid":"3671b77e-104c-4401-b553-d4a6f5f0e24b",
                "firstName":"Vova",
                "lastName":"Petruk"
            },
            "recipient":{
                "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
                "firstName":"Alex",
                "lastName":"Belozierov"
            },
            "commentsCount":1,
            "reactionsCount":0,
            "createdDate":"2019-07-30T12:18:59.319Z",
            "lastModifiedDate":"2019-07-30T12:18:59.318Z",
            "media":[
            ],
            "location":{
                "id":"5d4035b32a8c780001784df9",
                "name":"Kyiv",
                "description":"Kyiv, Ukraine, 02000",
                "icon":null,
                "latitude":50.4501,
                "longitude":30.523400000000038
            },
            "linkPreview":null,
            "settings":{
                "privacySettings":"EVERYONE",
                "commenting":true,
                "postponePublication":false,
                "postponePublicationDate":null
            },
            "taggedFriends":[
            ],
            "sharesCount":2,
            "sharedPost":null,
            "isContentUnavailable":false,
            "isAdvertised":false,
            "isLiked":false,
            "isAdvertisable":false
        },
        "taggedFriends":[
        ],
        "sharesCount":0,
        "sharedPost":{
            "id":"5d4035b32a8c780111784dfa",
            "body":null,
            "owner":{
                "uuid":"3671b77e-104c-4401-b553-d4a6f5f0e24b",
                "firstName":"Vova",
                "lastName":"Petruk"
            },
            "recipient":{
                "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
                "firstName":"Alex",
                "lastName":"Belozierov"
            },
            "commentsCount":1,
            "reactionsCount":0,
            "createdDate":"2019-07-30T12:18:59.319Z",
            "lastModifiedDate":"2019-07-30T12:18:59.318Z",
            "media":[
            ],
            "location":{
                "id":"5d4034b33a8c780001784df9",
                "name":"Kyiv",
                "description":"Kyiv, Ukraine, 02000",
                "icon":null,
                "latitude":50.4501,
                "longitude":30.523400000000038
            },
            "linkPreview":null,
            "settings":{
                "privacySettings":"EVERYONE",
                "commenting":true,
                "postponePublication":false,
                "postponePublicationDate":null
            },
            "originPost":null,
            "taggedFriends":[
            ],
            "sharesCount":2,
            "isContentUnavailable":false,
            "isAdvertised":false,
            "isLiked":false,
            "isAdvertisable":false
        },
        "isContentUnavailable":false,
        "isAdvertised":false,
        "isLiked":false,
        "isAdvertisable":false
    },
    {
        "id":"5d4035b32a8c780111784dfa",
        "body":null,
        "owner":{
            "uuid":"3671b77e-104c-4401-b553-d4a6f5f0e24b",
            "firstName":"Vova",
            "lastName":"Petruk"
        },
        "recipient":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "commentsCount":1,
        "reactionsCount":0,
        "createdDate":"2019-07-30T12:18:59.319Z",
        "lastModifiedDate":"2019-07-30T12:18:59.318Z",
        "media":[
        ],
        "location":{
            "id":"5d4035b32a8c780001784df9",
            "name":"Kyiv",
            "description":"Kyiv, Ukraine, 02000",
            "icon":null,
            "latitude":50.4501,
            "longitude":30.523400000000038
        },
        "linkPreview":null,
        "settings":{
            "privacySettings":"EVERYONE",
            "commenting":true,
            "postponePublication":false,
            "postponePublicationDate":null
        },
        "originPost":null,
        "taggedFriends":[
        ],
        "sharesCount":2,
        "sharedPost":null,
        "isContentUnavailable":false,
        "isAdvertised":false,
        "isLiked":false,
        "isAdvertisable":false
    },
    {
        "id":"5d402ebf9177a900016f0902",
        "body":"hello",
        "owner":{
            "uuid":"3671b77e-104c-4401-b553-d4a6f5f0e24b",
            "firstName":"Vova",
            "lastName":"Petruk"
        },
        "recipient":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "commentsCount":0,
        "reactionsCount":0,
        "createdDate":"2019-07-30T11:49:19.135Z",
        "lastModifiedDate":"2019-07-30T11:49:19.134Z",
        "media":[
        ],
        "location":{
            "id":"5d412ebf9177a910016f0901",
            "name":"Lviv Danylo Halytskyi International Airport",
            "description":"Liubinska St, 168, Lviv, L'vivs'ka oblast, Ukraine, 79000",
            "icon":null,
            "latitude":49.81344310000001,
            "longitude":23.959550400000012
        },
        "linkPreview":null,
        "settings":{
            "privacySettings":"EVERYONE",
            "commenting":true,
            "postponePublication":false,
            "postponePublicationDate":null
        },
        "originPost":null,
        "taggedFriends":[
        ],
        "sharesCount":1,
        "sharedPost":null,
        "isContentUnavailable":false,
        "isAdvertised":false,
        "isLiked":false,
        "isAdvertisable":false
    },
    {
        "id":"5d402368f8b8100001a6fdb8",
        "body":null,
        "owner":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "recipient":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "commentsCount":0,
        "reactionsCount":1,
        "createdDate":"2019-07-30T11:00:56.751Z",
        "lastModifiedDate":"2019-07-30T11:00:56.751Z",
        "media":[
            {
                "id":"5d402368f8b8100001a6fdb7",
                "content":"https://image.shutterstock.com/image-photo/white-transparent-leaf-on-mirror-600w-1029171697.jpg",
                "type":"PHOTO",
                "fileType":"video/mp4",
                "isInFavorite":false,
                "owner":{
                    "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
                    "firstName":"Alex",
                    "lastName":"Belozierov"
                },
                "order":0,
                "createdDate":"2019-07-30T11:00:56.748Z",
                "lastModifiedDate":"2019-07-30T11:00:56.748Z",
                "advertised":false
            }
        ],
        "location":null,
        "linkPreview":null,
        "settings":{
            "privacySettings":"EVERYONE",
            "commenting":true,
            "postponePublication":null,
            "postponePublicationDate":null
        },
        "originPost":null,
        "taggedFriends":[
        ],
        "sharesCount":0,
        "sharedPost":null,
        "isContentUnavailable":false,
        "isAdvertised":false,
        "isLiked":true,
        "isAdvertisable":true
    },
    {
        "id":"5d3eb123d8b8100001a6f91e",
        "body":"asdassdfsdf",
        "owner":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "recipient":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "commentsCount":0,
        "reactionsCount":1,
        "createdDate":"2019-07-29T08:45:23.075Z",
        "lastModifiedDate":"2019-07-29T08:45:23.075Z",
        "media":[
        ],
        "location":{
            "id":"5d3eb213f5b8200001a6f91d",
            "name":"Destin",
            "description":"Destin, FL 32541, USA",
            "icon":null,
            "latitude":30.39353369999999,
            "longitude":-86.49578329999997
        },
        "linkPreview":null,
        "settings":{
            "privacySettings":"EVERYONE",
            "commenting":true,
            "postponePublication":null,
            "postponePublicationDate":null
        },
        "originPost":null,
        "taggedFriends":[
        ],
        "sharesCount":0,
        "sharedPost":null,
        "isContentUnavailable":false,
        "isAdvertised":false,
        "isLiked":true,
        "isAdvertisable":true
    },
    {
        "id":"5d49bf212b8c780101783e4f",
        "body":null,
        "owner":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "recipient":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "commentsCount":2,
        "reactionsCount":1,
        "createdDate":"2019-07-25T14:39:13.957Z",
        "lastModifiedDate":"2019-07-25T14:39:13.948Z",
        "media":[
        ],
        "location":{
            "id":"6d39bf112a8c78010178324e",
            "name":"Rio de Janeiro",
            "description":"Rio de Janeiro, State of Rio de Janeiro, Brazil",
            "icon":null,
            "latitude":-22.9068467,
            "longitude":-43.17289649999998
        },
        "linkPreview":null,
        "settings":{
            "privacySettings":"EVERYONE",
            "commenting":true,
            "postponePublication":null,
            "postponePublicationDate":null
        },
        "originPost":null,
        "taggedFriends":[
        ],
        "sharesCount":0,
        "sharedPost":null,
        "isContentUnavailable":false,
        "isAdvertised":false,
        "isLiked":true,
        "isAdvertisable":true
    },
    {
        "id":"5d3858ea4b59140001e20bac",
        "body":"my post",
        "owner":{
            "uuid":"3671b77e-104c-4401-b553-d4a6f5f0e24b",
            "firstName":"Vova",
            "lastName":"Petruk"
        },
        "recipient":{
            "uuid":"3671b77e-104c-4401-b553-d4a6f5f0e24b",
            "firstName":"Vova",
            "lastName":"Petruk"
        },
        "commentsCount":22,
        "reactionsCount":2,
        "createdDate":"2019-07-24T13:11:06.786Z",
        "lastModifiedDate":"2019-07-24T13:11:06.785Z",
        "media":[
        ],
        "location":null,
        "linkPreview":null,
        "settings":{
            "privacySettings":"FRIENDS",
            "commenting":true,
            "postponePublication":null,
            "postponePublicationDate":null
        },
        "originPost":null,
        "taggedFriends":[
            {
                "uuid":"ab817255-dc30-4223-9ff9-f0cb571c35c0",
                "firstName":"Taras",
                "lastName":"Bulba"
            },
            {
                "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
                "firstName":"Alex",
                "lastName":"Belozierov"
            },
            {
                "uuid":"fba346fb-f3f5-4df5-aa47-9c13448f365e",
                "firstName":"Ivan",
                "lastName":"petrenko"
            }
        ],
        "sharesCount":0,
        "sharedPost":null,
        "isContentUnavailable":false,
        "isAdvertised":false,
        "isLiked":true,
        "isAdvertisable":false
    },
    {
        "id":"5d383b8d4b59150101e10b80",
        "body":"s kads ajhsd qewyiuq eouiqwye uqydoiqjdiq e uqwud qjsdlqj wlejql jda jsdiquweuq sdua jdqjw eoiqueq wdojalsdj qioweu ioqwus kads ajhsd qewyiuq eouiqwye uqydoiqjdiq e uqwud qjsdlqj wlejql jda jsdiquweuq sdua jdqjw eoiqueq wdojalsdj qioweu ioqwus kads ajhsd qewyiuq eouiqwye uqydoiqjdiq e uqwud qjsdlqj wlejql jda jsdiquweuq sdua jdqjw eoiqueq wdojalsdj qioweu ioqwus kads ajhsd qewyiuq eouiqwye uqydoiqjdiq e uqwud qjsdlqj wlejql jda jsdiquweuq sdua jdqjw eoiqueq wdojalsdj qioweu ioqwus kads ajhsd qewyiuq eouiqwye uqydoiqjdiq e uqwud qjsdlqj wlejql jda jsdiquweuq sdua jdqjw eoiqueq wdojalsdj qioweu ioqwus kads ajhsd qewyiuq eouiqwye uqydoiqjdiq e uqwud qjsdlqj wlejql jda jsdiquweuq sdua jdqjw eoiqueq wdojalsdj qioweu ioqwus kads ajhsd qewyiuq eouiqwye uqydoiqjdiq e uqwud qjsdlqj wlejql jda jsdiquweuq sdua jdqjw eoiqueq wdojalsdj qioweu ioqwus kads ajhsd qewyiuq eouiqwye uqydoiqjdiq e uqwud qjsdlqj wlejql jda jsdiquweuq sdua jdqjw eoiqueq wdojalsdj qioweu ioqwus kads ajhsd qewyiuq eouiqwye uqydoiqjdiq e uqwud qjsdlqj wlejql jda jsdiquweuq sdua jdqjw eoiqueq wdojalsdj qioweu ioqwus kads ajhsd qewyiuq eouiqwye uqydoiqjdiq e uqwud qjsdlqj wlejql jda jsdiquweuq sdua jdqjw eoiqueq wdojalsdj qioweu ioqwus kads ajhsd qewyiuq eouiqwye uqydoiqjdiq e uqwud qjsdlqj wlejql jda jsdiquweuq sdua jdqjw eoiqueq wdojalsdj qioweu ioqwus kads ajhsd qewyiuq eouiqwye uqydoiqjdiq e uqwud qjsdlqj wlejql jda jsdiquweuq sdua jdqjw eoiqueq wdojalsdj qioweu ioqwus kads ajhsd qewyiuq eouiqwye uqydoiqjdiq e uqwud qjsdlqj wlejql jda jsdiquweuq sdua jdqjw eoiqueq wdojalsdj qioweu ioqwu",
        "owner":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "recipient":{
            "uuid":"cf5bdd2a-0c44-449a-b1ed-6d8f1adce266",
            "firstName":"Alex",
            "lastName":"Belozierov"
        },
        "commentsCount":4,
        "reactionsCount":0,
        "createdDate":"2019-07-24T11:01:33.309Z",
        "lastModifiedDate":"2019-07-24T11:01:33.308Z",
        "media":[
        ],
        "location":null,
        "linkPreview":null,
        "settings":{
            "privacySettings":"EVERYONE",
            "commenting":true,
            "postponePublication":null,
            "postponePublicationDate":null
        },
        "originPost":null,
        "taggedFriends":[
        ],
        "sharesCount":0,
        "sharedPost":null,
        "isContentUnavailable":false,
        "isAdvertised":false,
        "isLiked":false,
        "isAdvertisable":true
    }
]
"""#
